### ISSUE TITLE
package ‘ggnomics’ is not available (for R version 3.6.1) neither ggh4x

### ISSUE THREAD

**Issue by Laurasheff** [teunbrand/ggnomics#39] opened 2020-04-23 12:01 UTC
Hi, 

I was using the wonderful function you made of facet_nested (just by pasting the code you posted elsewhere) and after the error of env (and know "object '.int' not found") you suggested to use genomics.
I am a newbie, and I do not know how to sort that out. 
Any ideas? 

Thanks

**Comment by teunbrand** [comment] 2020-04-23 13:04
Hi,

This package (ggnomics) no longer supports `facet_nested()` in the future and I have moved this function to the `ggh4x` package where it will be maintained. An error message similar to yours was reported there: https://github.com/teunbrand/ggh4x/issues/8. That person resolved their error by installing the ggh4x package instead of copy-pasting the function.

If you have ggplot2 v3.3.0 (the most recent on CRAN at the time of writing this), you should be able to install ggh4x by using
```
devtools::install_github("teunbrand/ggh4x")
```
Then `facet_nested()` should work as intended.

Would you mind linking to the post you found the code, so I could try to edit the post in order to prevent this misunderstanding in the future?

Best wishes

**Comment by teunbrand** [comment] 2020-06-19 19:37
I'm closing this as it is more an issue appropriate for ggh4x

**Closed as completed by teunbrand** 2020-06-19 19:37 UTC
